import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // Onboarding
        navDashboard: 'Dashboard',
        navLogin: 'Login',
        navGetStarted: 'Get Started',
        heroTitle1: 'Global Trade',
        heroTitle2: 'Made',
        heroTitle3: 'Simple.',
        heroSubtitle1: 'The most powerful platform for modern importers.',
        heroSubtitle2: 'Secure, high-speed, and designed for your growth.',
        createFreeAccount: 'Create Your Free Account',
        downloadOnThe: 'Download on the',
        getItOn: 'Get it on',
        appStore: 'App Store',
        googlePlay: 'Google Play',
        footerRights: '© 2026 IMPORTERS APPLICATION. ALL RIGHTS RESERVED.',

        // Sidebar
        dashboard: 'Dashboard',
        clientCommands: 'Client Commands',
        negotiations: 'Negotiations',
        myOffers: 'My Offers',
        orders: 'Orders',
        wallet: 'Wallet',
        settings: 'Settings',

        // Dashboard
        dashboardTitle: 'Dashboard',
        dashboardSubtitle: "Welcome back! Here's what's happening with your business.",
        activeCommands: 'Active Commands',
        activeNegotiations: 'Active Negotiations',
        noNegotiationsFound: 'No negotiations yet. Start exploring commands to find deals!',
        selectNegotiation: 'Select a conversation to start negotiating',
        relatesToOffer: 'Relates to Offer',
        incomingProposal: 'Incoming Proposal',
        totalValue: 'Total Value',
        makeCounterOffer: 'Make a Counter Offer',
        newPrice: 'New Price',
        newQuantity: 'New Quantity',
        sendCounterOffer: 'Send Counter Offer',
        negotiationDesc: 'Review proposals, counter prices, and finalize your global trade deals in real-time.',
        directComm: 'Direct Communication',
        securePayments: 'Secure Payments',
        priceNeg: 'Price Negotiation',
        typeAMessage: 'Type a message...',
        activeOrders: 'Active Orders',
        pointsBalance: 'Points Balance',
        earningsOverview: 'Revenue Overview',
        monthlyEarnings: 'Monthly earnings trend',
        revenueTrend: 'Monthly earnings trend',
        requestDetails: 'Request Details',
        searchPlaceholder: 'Search...',
        last6Months: 'Last 6 months',
        last12Months: 'Last 12 months',
        thisYear: 'This year',
        ordersByStatus: 'Orders by Status',
        completed: 'Completed',
        inProgress: 'In Progress',
        pending: 'Pending',
        cancelled: 'Cancelled',
        quickActions: 'Quick Actions',
        createOffer: 'Create Offer',
        createOfferDesc: 'Publish a new product to the platform',
        browseCommands: 'Browse Commands',
        thisMonth: 'This Month',
        totalEarnings: 'Total Earnings',
        ordersCompleted: 'Orders Completed',
        avgRating: 'Avg. Rating',
        recentActivity: 'Recent Activity',
        orderId: 'Order ID',
        client: 'Client',
        vendor: 'Vendor',
        action: 'Action',
        amount: 'Amount',
        time: 'Time',
        status: 'Status',
        // Months
        jan: 'Jan',
        feb: 'Feb',
        mar: 'Mar',
        apr: 'Apr',
        may: 'May',
        jun: 'Jun',
        jul: 'Jul',
        aug: 'Aug',
        sep: 'Sep',
        oct: 'Oct',
        nov: 'Nov',
        dec: 'Dec',
        // Activity statuses
        statusNew: 'new',
        statusPaid: 'paid',
        statusNegotiating: 'negotiating',
        statusACTIVE: 'Active',
        statusHIDDEN: 'Hidden',
        statusPENDING: 'Pending',
        statusAPPROVED: 'Approved',
        statusREJECTED: 'Rejected',
        pendingActionError: '🔒 Identity Verification in Progress: You’re currently in read-only mode. Once our team approves your documents, you’ll have full access. We’ll notify you at your registered email!',
        selectNegotiationPlaceholder: 'Select a negotiation to start chatting with clients and close deals.',
        workspaceTitle: 'Your Workspace',
        proposedPriceLabel: 'Proposed Price',
        proposedQuantityLabel: 'Proposed Quantity',
        willNotifyEmail: 'Notification will be sent to:',
        // Activity Actions
        actNewProposal: 'New proposal received',
        actOrderCompleted: 'Order completed',
        actPaymentReceived: 'Payment received',
        actNegotiationStarted: 'Negotiation started',

        // My Offers
        myOffersTitle: 'My Offers',
        myOffersSubtitle: 'Manage your product offerings',
        image: 'Image',
        title: 'Title',
        basePrice: 'Base Price',
        availableQty: 'Available Qty',
        origin: 'Origin',
        negotiable: 'Negotiable',
        actions: 'Actions',
        loadingOffers: 'Loading offers...',
        noOffersFound: 'No offers found. Create your first offer!',
        units: 'units',
        deleteOffer: 'Delete Offer',
        deleteOfferMsg: 'Are you sure you want to delete this offer? this action cannot be undone.',
        delete: 'Delete',
        keepIt: 'Keep it',

        // Orders
        ordersTitle: 'Orders',
        ordersSubtitle: 'Manage your import orders',
        total: 'Total',
        escrowStatus: 'Escrow Status',
        orderStatus: 'Order Status',
        createdAt: 'Created At',
        viewDetails: 'View Details',
        backToOrders: 'Back to Orders',
        createdOn: 'Created on',
        orderItems: 'Order Items',
        shipmentProof: 'Shipment Proof',
        noShipmentDocs: 'No shipment documents yet',
        markAsShipped: 'Mark as Shipped',
        inspectionVideo: 'Inspection Video',
        uploadInspectionVideo: 'Upload inspection video once shipped',
        uploadVideo: 'Upload Video',
        escrowDetails: 'Escrow Details',
        depositAmount: 'Deposit Amount',
        totalHeld: 'Total Held',
        releasedAmount: 'Released Amount',
        escrowProgress: 'Escrow Progress',
        actionsCard: 'Actions',
        contactClient: 'Contact Client',
        escrowHeld: 'held',
        escrowReleased: 'released',
        orderProcessing: 'processing',
        orderCompleted: 'completed',

        // Client Commands
        clientCommandsTitle: 'Client Commands',
        clientCommandsSubtitle: 'Browse and respond to import requests',
        searchCommands: 'Search commands...',
        allCategories: 'All Categories',
        electronics: 'Electronics',
        clothing: 'Clothing',
        furniture: 'Furniture',
        moreFilters: 'More Filters',
        launchDate: 'Launch Date',
        originWilaya: 'Origin (Wilaya)',
        allLocations: 'All Locations',
        allStatus: 'All Status',
        urgent: 'Urgent',
        normal: 'Normal',
        statusNew2: 'New',
        budgetRange: 'Budget Range',
        min: 'Min',
        max: 'Max',
        qty: 'Qty',
        deadline: 'Deadline',
        seeMore: 'See more',
        sendProposal: 'Send Proposal',
        commandDetails: 'Command Details',
        commandId: 'Command ID',
        product: 'Product',
        quantity: 'Quantity',
        budget: 'Budget',
        location: 'Location',
        category: 'Category',
        budgetRangeLabel: 'Budget Range',
        proposedUnitPrice: 'Proposed Unit Price (€)',
        unitPrice: 'Price per Unit (DZD) *',
        enterPricePerUnit: 'Enter your price per unit',
        yourProposal: 'Your Proposal Message',
        quantityOffered: 'Quantity Offered',
        deliveryTime: 'Delivery Time (days)',
        messageToClient: 'Message to Client',
        describeOffer: 'Describe your offer, quality guarantees, shipping details...',
        beSpecific: 'Be specific about quality and conditions.',
        warningContact: 'Warning: Sharing external contact info (WhatsApp, Email, etc.) is strictly prohibited. Our AI system will detect this instantly and your account will be PERMANENTLY BANNED without appeal.',
        securityWarning: '⚠️ IMMEDIATE BAN RISK',
        saveDraft: 'Draft',
        posted2DaysAgo: 'Posted 2 days ago',
        posted5DaysAgo: 'Posted 5 days ago',
        posted1WeekAgo: 'Posted 1 week ago',
        delivery7to10Days: '7 - 10 days',
        delivery10to15Days: '10 - 15 days',
        delivery15to20Days: '15 - 20 days',
        delivery20to30Days: '20 - 30 days',
        deliveryMore30Days: '+30 days',
        publishingOffer: 'Publishing your offer...',
        updatingOffer: 'Updating your offer...',
        createNewOffer: 'Create New Offer',
        orderTracking: 'Order Details',
        editOfferTitle: 'Edit Offer',
        productDetails: 'Product Details',
        pricingQuantity: 'Pricing & Quantity',
        imagesOrigin: 'Images & Origin',
        basicInfo: 'Basic Info',
        mediaOrigin: 'Media & Origin',
        offerPublishedSuccess: 'Offer Published Successfully!',
        offerUpdatedSuccess: 'Offer Updated Successfully!',
        offerPublishedSuccessMsg: 'Your product is now live and visible to potential clients.',
        offerUpdatedSuccessMsg: 'Your changes have been saved.',
        done: 'Done',
        titleLabel: 'Title',
        titlePlaceholder: 'e.g., Premium Leather Jackets Offer',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Detailed product description...',
        productNameLabel: 'Product Name',
        productNamePlaceholder: 'e.g., Leather Jacket model X',
        categoryLabel: 'Category',
        selectCategory: 'Select category',
        fashion: 'Fashion',
        electronicsCat: 'Electronics',
        homeGarden: 'Home & Garden',
        automotive: 'Automotive',
        basePriceLabel: 'Base Price ($)',
        availableQtyLabel: 'Available Quantity',
        priceNegotiable: 'Price is negotiable',
        negotiableAgreeMsg: 'By selecting this, you agree to receive negotiation requests for this offer.',
        productImages: 'Product Images',
        upload: 'Upload',
        uploadHint: 'Upload up to 8 images',
        selected: 'selected',
        originCountry: 'Origin Country',
        originPlaceholder: 'e.g., Italy, China',
        preview: 'Preview',
        noDescription: 'No description',
        updateOffer: 'Update offer',
        publishOffer: 'Publish offer',
        continue: 'Continue',
        errReqTitle: 'Please enter a title for your offer',
        errReqDesc: 'Please enter a product description',
        errReqProdName: 'Please enter a product name',
        errReqCat: 'Please select a category',
        errReqPrice: 'Please enter a valid base price',
        errReqQty: 'Please enter a valid available quantity',
        errReqImages: 'Please upload at least one product image',
        errReqOrigin: 'Please enter the country of origin',
        errMaxImages: 'Maximum 8 images allowed. Please select fewer files.',
        brandLogo: 'Importer',
        logout: 'Logout',
        discoverDeals: 'Discover Deals',
        noOrdersMsg: 'No orders found yet. Start browsing deals to make your first trade!',

        // Auth Pages (Login & SignUp)
        loginTitle: 'importers',
        loginSubtitle: 'Welcome back! Please login to your account.',
        emailLabel: 'Email',
        emailPlaceholder: 'your.email@example.com',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Enter your password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        loginButton: 'Login',
        loggingInButton: 'Logging in...',
        noAccount: "Don't have an account?",
        registerAsBusiness: 'Register as Business',
        loginFooter: '© 2026 Importers. All rights reserved.',

        signupMainTitle: 'importers',
        signupSubtitle: 'Register your business account',
        businessNameLabel: 'Business Name',
        businessNamePlaceholder: 'Enter business name',
        ownerNameLabel: 'Owner Full Name',
        ownerNamePlaceholder: "Enter owner's full name",
        commerceNumLabel: 'Register Commerce Number',
        commerceNumPlaceholder: 'Enter commerce number',
        ninLabel: 'NIN (National Identification Number)',
        ninPlaceholder: 'Enter NIN',
        importLicenseLabel: 'Import License',
        commRegisterLabel: 'Commercial Register',
        idFrontLabel: 'ID Front',
        idBackLabel: 'ID Back',
        clickToUpload: 'Click to upload',
        liveSelfieVerif: 'Live Selfie Verification',
        liveSelfieDesc: 'Please capture a clear photo of yourself',
        readyToSubmit: 'Ready to submit',
        retakePhoto: 'Retake Photo',
        clickToOpenCam: 'Click to open camera',
        phoneLabel: 'Phone',
        confirmPasswordLabel: 'Confirm Password',
        confirmPasswordPlaceholder: 'Confirm your password',
        backButton: 'Back',
        nextButton: 'Next',
        registerButton: 'Register Business',
        haveAccount: 'Already have an account?',
        loginLink: 'Login',
        step1: 'Register',
        step2: 'Documents',
        step3: 'Selfie',
        step4: 'Credential',

        // Auth Errors
        errInvalidCreds: 'Please enter valid credentials.',
        errAccountReview: 'Your account is still under review. Please wait 24-48 hours.',
        errAccountNotFound: 'Account not found.',
        errLoginFailed: 'Login failed. Please try again.',
        errNetwork: 'Network error: Server is unreachable or CORS blocked.',
        errReqBusinessName: 'Business Name is required.',
        errReqOwnerName: 'Owner Full Name is required.',
        errReqCommerceNum: 'Register Commerce Number is required.',
        errReqNin: 'NIN is required.',
        errNinLength: 'NIN must be exactly 18 digits.',
        errReqIdFront: 'ID Front image is required.',
        errReqImportLicense: 'Import License is required.',
        errReqCommRegister: 'Commercial Register is required.',
        errReqSelfie: 'Selfie photo is required.',
        errSelfieMissing: 'Selfie photo is missing or invalid.',
        errSelfieProcess: 'Error processing selfie photo. Please try retaking it.',
        errReqEmail: 'Email is required.',
        errInvalidEmail: 'Email format is invalid.',
        errReqPhone: 'Phone number is required.',
        errPhoneLength: 'Phone number must have 9 digits after the prefix.',
        errReqPassword: 'Password is required.',
        errPasswordMismatch: 'Passwords do not match.',
        errInvalidData: 'Invalid data. Please check your inputs.',
        errRegistrationData: 'Please correct the following errors:',
        errSecurityVerif: 'Security Verification',
        errSentCodeTo: 'We\'ve sent a 6-digit code to',
        errInvalidOtpMsg: 'Please enter a valid 6-digit OTP code.',
        errVerifyOtp: 'Invalid OTP. Please try again.',
        errOtpResendFailed: 'Failed to resend OTP. Please try again.',
        errOccurredDuringReg: 'An error occurred during registration.',

        // Settings Page
        settingsTitle: 'Settings & Profile',
        settingsSubtitle: 'Manage your account and preferences',
        businessProfile: 'Business Profile',
        verificationDocs: 'Verification Documents',
        notificationPrefs: 'Notification Preferences',
        profilePicture: 'Profile Picture',
        language: 'Language',
        security: 'Security',
        businessName: 'Business Name',
        ownerFullName: 'Owner Full Name',
        email: 'Email',
        phone: 'Phone',
        businessAddress: 'Business Address',
        taxId: 'Tax ID',
        website: 'Website',
        saveChanges: 'Save Changes',
        uploadNew: 'Upload New',
        changePassword: 'Change Password',
        twoFactorAuth: 'Two-Factor Auth',
        approved: 'Approved',
        reupload: 'Reupload',
        uploaded: 'Uploaded',
        stayUpdated: 'Stay updated with what matters most to you',
        emailNotifications: 'Email Notifications',
        pushNotifications: 'Push Notifications',
        orderUpdates: 'Order Updates',
        negotiationMessages: 'Negotiation messages',
        promotionsUpdates: 'Promotions and updates',
        statusPublished: 'Published',
        statusDraft: 'Draft',
        statusPending: 'Pending',
        statusHidden: 'Hidden',
        hide: 'Hide',
        manageBusinessDesc: 'Manage your core business details',
        verifyIdentityDesc: 'Verify your identity to unlock all features',
        roleImporter: 'Importer',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        updatePassword: 'Update Password',
        saving: 'Saving changes...',
        profileUpdated: 'Profile updated successfully',
        errorSaving: 'Failed to save changes',
        update: 'Update',
        updatingPassword: 'Updating password...',
        passwordUpdated: 'Password updated successfully!',
        passwordsMismatch: "Passwords don't match!"
    },

    ar: {
        // Onboarding
        navDashboard: 'لوحة التحكم',
        navLogin: 'تسجيل الدخول',
        navGetStarted: 'ابدأ الآن',
        heroTitle1: 'التجارة العالمية',
        heroTitle2: 'أصبحت',
        heroTitle3: 'بسيطة.',
        heroSubtitle1: 'المنصة الأقوى للمستوردين العصريين.',
        heroSubtitle2: 'آمنة، سريعة، ومصممة لنمو أعمالك.',
        createFreeAccount: 'أنشئ حسابك المجاني',
        downloadOnThe: 'حمل من',
        getItOn: 'احصل عليه من',
        appStore: 'أب ستور',
        googlePlay: 'جوجل بلاي',
        footerRights: '© 2026 تطبيق المستوردين. جميع الحقوق محفوظة.',

        // Sidebar
        dashboard: 'لوحة التحكم',
        clientCommands: 'طلبات العملاء',
        negotiations: 'المفاوضات',
        myOffers: 'عروضي',
        orders: 'الطلبات',
        wallet: 'المحفظة',
        settings: 'الإعدادات',

        // Dashboard
        dashboardTitle: 'لوحة التحكم',
        dashboardSubtitle: 'مرحباً بعودتك! إليك ما يجري في عملك.',
        activeCommands: 'الطلبات النشطة',
        activeNegotiations: 'المفاوضات النشطة',
        noNegotiationsFound: 'لا توجد مفاوضات بعد. ابدأ في تصفح الطلبات لإيجاد صفقات!',
        selectNegotiation: 'اختر محادثة لبدء التفاوض',
        relatesToOffer: 'مرتبط بالعرض',
        incomingProposal: 'عرض وارد',
        totalValue: 'القيمة الإجمالية',
        makeCounterOffer: 'تقديم عرض مقابل',
        newPrice: 'السعر الجديد',
        newQuantity: 'الكمية الجديدة',
        sendCounterOffer: 'إرسال العرض المقابل',
        negotiationDesc: 'راجع العروض، فاوض على الأسعار، وأتمم صفقات التجارة العالمية في الوقت الفعلي.',
        directComm: 'اتصال مباشر',
        securePayments: 'دفع آمن',
        priceNeg: 'تفاوض على السعر',
        typeAMessage: 'اكتب رسالة...',
        activeOrders: 'الأوامر النشطة',
        pointsBalance: 'رصيد النقاط',
        earningsOverview: 'نظرة عامة على الأرباح',
        monthlyEarnings: 'الاتجاه الشهري للأرباح',
        revenueTrend: 'الاتجاه الشهري للأرباح',
        requestDetails: 'تفاصيل الطلب',
        searchPlaceholder: 'بحث...',
        last6Months: 'آخر 6 أشهر',
        last12Months: 'آخر 12 شهراً',
        thisYear: 'هذا العام',
        ordersByStatus: 'الطلبات حسب الحالة',
        completed: 'مكتملة',
        inProgress: 'قيد التنفيذ',
        pending: 'معلقة',
        cancelled: 'ملغاة',
        quickActions: 'الإجراءات السريعة',
        createOffer: 'إنشاء عرض',
        createOfferDesc: 'انشر منتجًا جديدًا على المنصة',
        browseCommands: 'تصفح الطلبات',
        thisMonth: 'هذا الشهر',
        totalEarnings: 'إجمالي الأرباح',
        ordersCompleted: 'الطلبات المكتملة',
        avgRating: 'متوسط التقييم',
        recentActivity: 'النشاط الأخير',
        orderId: 'رقم الطلب',
        client: 'العميل',
        vendor: 'المورد',
        action: 'الإجراء',
        amount: 'المبلغ',
        time: 'الوقت',
        status: 'الحالة',
        // Months (Algerian)
        jan: 'جانفي',
        feb: 'فيفري',
        mar: 'مارس',
        apr: 'افريل',
        may: 'ماي',
        jun: 'جوان',
        jul: 'جويلية',
        aug: 'اوت',
        sep: 'سبتمبر',
        oct: 'اكتوبر',
        nov: 'نوفمبر',
        dec: 'ديسمبر',
        statusNew: 'جديد',
        statusPaid: 'مدفوع',
        statusNegotiating: 'قيد التفاوض',
        statusACTIVE: 'نشط',
        statusHIDDEN: 'مخفي',
        statusPENDING: 'قيد المراجعة',
        statusAPPROVED: 'مقبول',
        statusREJECTED: 'مرفوض',
        pendingActionError: '🔒 جاري التحقق من الهوية: أنت الآن في وضع القراءة فقط. بمجرد موافقة فريقنا على مستنداتك، سيكون لديك وصول كامل. سنقوم بإخطارك عبر بريدك الإلكتروني المسجل!',
        selectNegotiationPlaceholder: 'اختر مفاوضة لبدء الدردشة مع العملاء وإتمام الصفقات.',
        workspaceTitle: 'مساحة عملك',
        proposedPriceLabel: 'السعر المقترح',
        proposedQuantityLabel: 'الكمية المقترحة',
        willNotifyEmail: 'سيتم إرسال الإشعار إلى:',
        actNewProposal: 'تم استلام عرض جديد',
        actOrderCompleted: 'تم إتمام الطلب',
        actPaymentReceived: 'تم استلام الدفعة',
        actNegotiationStarted: 'بدأت المفاوضة',

        // My Offers
        myOffersTitle: 'عروضي',
        myOffersSubtitle: 'إدارة عروضك التجارية',
        image: 'الصورة',
        title: 'العنوان',
        basePrice: 'السعر الأساسي',
        availableQty: 'الكمية المتاحة',
        origin: 'المنشأ',
        negotiable: 'قابل للتفاوض',
        actions: 'الإجراءات',
        loadingOffers: 'جاري تحميل العروض...',
        noOffersFound: 'لا توجد عروض. أنشئ عرضك الأول!',
        units: 'وحدة',
        deleteOffer: 'حذف العرض',
        deleteOfferMsg: 'هل أنت متأكد من حذف هذا العرض؟ لا يمكن التراجع عن هذا الإجراء.',
        delete: 'حذف',
        keepIt: 'الاحتفاظ به',

        // Orders
        ordersTitle: 'الطلبات',
        ordersSubtitle: 'إدارة طلبات الاستيراد الخاصة بك',
        total: 'الإجمالي',
        escrowStatus: 'حالة الضمان',
        orderStatus: 'حالة الطلب',
        createdAt: 'تاريخ الإنشاء',
        viewDetails: 'عرض التفاصيل',
        backToOrders: 'العودة إلى الطلبات',
        createdOn: 'تم الإنشاء في',
        orderItems: 'عناصر الطلب',
        shipmentProof: 'إثبات الشحن',
        noShipmentDocs: 'لا توجد وثائق شحن بعد',
        markAsShipped: 'تحديد كمشحون',
        inspectionVideo: 'فيديو الفحص',
        uploadInspectionVideo: 'ارفع فيديو الفحص بعد الشحن',
        uploadVideo: 'رفع الفيديو',
        escrowDetails: 'تفاصيل الضمان',
        depositAmount: 'مبلغ الوديعة',
        totalHeld: 'الإجمالي المحتجز',
        releasedAmount: 'المبلغ المُفرج عنه',
        escrowProgress: 'تقدم الضمان',
        actionsCard: 'الإجراءات',
        contactClient: 'التواصل مع العميل',
        escrowHeld: 'محتجز',
        escrowReleased: 'مُفرج عنه',
        orderProcessing: 'قيد المعالجة',
        orderCompleted: 'مكتمل',

        // Client Commands
        clientCommandsTitle: 'طلبات العملاء',
        clientCommandsSubtitle: 'تصفح طلبات الاستيراد والرد عليها',
        searchCommands: 'البحث في الطلبات...',
        allCategories: 'جميع الفئات',
        electronics: 'الإلكترونيات',
        clothing: 'الملابس',
        furniture: 'الأثاث',
        moreFilters: 'مزيد من الفلاتر',
        launchDate: 'تاريخ الإطلاق',
        originWilaya: 'الولاية الأصلية',
        allLocations: 'جميع المناطق',
        allStatus: 'جميع الحالات',
        urgent: 'عاجل',
        normal: 'عادي',
        statusNew2: 'جديد',
        budgetRange: 'نطاق الميزانية',
        min: 'الحد الأدنى',
        max: 'الحد الأقصى',
        qty: 'الكمية',
        deadline: 'الموعد النهائي',
        seeMore: 'عرض المزيد',
        sendProposal: 'إرسال عرض',
        commandDetails: 'تفاصيل الطلب',
        commandId: 'رقم الطلب',
        product: 'المنتج',
        quantity: 'الكمية',
        budget: 'الميزانية',
        location: 'الموقع',
        category: 'الفئة',
        budgetRangeLabel: 'نطاق الميزانية',
        proposedUnitPrice: 'سعر الوحدة المقترح (€)',
        unitPrice: 'سعر الوحدة (د.ج) *',
        enterPricePerUnit: 'أدخل سعرك للوحدة',
        quantityOffered: 'الكمية المعروضة',
        deliveryTime: 'وقت التسليم (أيام)',
        messageToClient: 'رسالة إلى العميل',
        describeOffer: 'صف عرضك، ضمانات الجودة، تفاصيل الشحن...',
        beSpecific: 'كن محدداً حول جودة المنتج والشهادات والشروط.',
        warningContact: 'تحذير: مشاركة معلومات الاتصال الخارجية (واتساب، إيميل، إلخ) ممنوعة تماماً. سيكتشف نظام الذكاء الاصطناعي لدينا ذلك فوراً وسيتم حظر حسابك نهائياً دون إمكانية الاستئناف.',
        securityWarning: '⚠️ خطر الحظر الفوري',
        posted2DaysAgo: 'تم النشر قبل يومين',
        posted5DaysAgo: 'تم النشر قبل 5 أيام',
        posted1WeekAgo: 'تم النشر قبل أسبوع',
        delivery7to10Days: '7 - 10 أيام',
        delivery10to15Days: '10 - 15 يومًا',
        delivery15to20Days: '15 - 20 يومًا',
        delivery20to30Days: '20 - 30 يومًا',
        deliveryMore30Days: '+30 يومًا',
        publishingOffer: 'جاري نشر عرضك...',
        updatingOffer: 'جاري تحديث عرضك...',
        createNewOffer: 'إنشاء عرض جديد',
        orderTracking: 'تفاصيل الطلب',
        editOfferTitle: 'تعديل العرض',
        productDetails: 'تفاصيل المنتج',
        pricingQuantity: 'التسعير والكمية',
        imagesOrigin: 'الصور والمنشأ',
        basicInfo: 'معلومات أساسية',
        mediaOrigin: 'الصور والمنشأ',
        offerPublishedSuccess: 'تم نشر العرض بنجاح!',
        offerUpdatedSuccess: 'تم تحديث العرض بنجاح!',
        offerPublishedSuccessMsg: 'منتجك الآن مباشر ومرئي للعملاء المحتملين.',
        offerUpdatedSuccessMsg: 'تم حفظ تغييراتك بنجاح.',
        done: 'تم',
        titleLabel: 'العنوان',
        titlePlaceholder: 'مثال: عرض جواكيت جلد فاخرة',
        descriptionLabel: 'الوصف',
        descriptionPlaceholder: 'وصف مفصل للمنتج...',
        productNameLabel: 'اسم المنتج',
        productNamePlaceholder: 'مثال: جاكيت جلد موديل X',
        categoryLabel: 'الفئة',
        selectCategory: 'اختر الفئة',
        fashion: 'أزياء',
        electronicsCat: 'إلكترونيات',
        homeGarden: 'المنزل والحديقة',
        automotive: 'سيارات',
        basePriceLabel: 'السعر الأساسي ($)',
        availableQtyLabel: 'الكمية المتاحة',
        priceNegotiable: 'السعر قابل للتفاوض',
        negotiableAgreeMsg: 'بتحديد هذا، فإنك توافق على تلقي طلبات التفاوض لهذا العرض.',
        productImages: 'صور المنتج',
        upload: 'رفع',
        uploadHint: 'ارفع ما يصل إلى 8 صور',
        selected: 'مختارة',
        originCountry: 'بلد المنشأ',
        originPlaceholder: 'مثال: إيطاليا، الصين',
        preview: 'معاينة',
        noDescription: 'لا يوجد وصف',
        updateOffer: 'تحديث العرض',
        publishOffer: 'نشر العرض',
        continue: 'متابعة',
        errReqTitle: 'يرجى إدخال عنوان لعرضك',
        errReqDesc: 'يرجى إدخال وصف للمنتج',
        errReqProdName: 'يرجى إدخال اسم المنتج',
        errReqCat: 'يرجى اختيار فئة',
        errReqPrice: 'يرجى إدخال سعر أساسي صحيح',
        errReqQty: 'يرجى إدخال كمية متاحة صحيحة',
        errReqImages: 'يرجى رفع صورة واحدة على الأقل للمنتج',
        errReqOrigin: 'يرجى إدخال بلد المنشأ',
        errMaxImages: 'الحد الأقصى هو 8 صور. يرجى اختيار عدد أقل.',
        brandLogo: 'المستورد',
        logout: 'تسجيل الخروج',
        discoverDeals: 'اكتشف الصفقات',
        noOrdersMsg: 'لم يتم العثور على طلبات بعد. ابدأ في تصفح العروض لإجراء أول صفقة لك!',

        // Auth Pages (Login & SignUp)
        loginTitle: 'المستوردين',
        loginSubtitle: 'مرحباً بعودتك! يرجى تسجيل الدخول إلى حسابك.',
        emailLabel: 'البريد الإلكتروني',
        emailPlaceholder: 'your.email@example.com',
        passwordLabel: 'كلمة المرور',
        passwordPlaceholder: 'أدخل كلمة المرور',
        rememberMe: 'تذكرني',
        forgotPassword: 'هل نسيت كلمة المرور؟',
        loginButton: 'تسجيل الدخول',
        loggingInButton: 'جاري تسجيل الدخول...',
        noAccount: "ليس لديك حساب؟",
        registerAsBusiness: 'سجل كشركة',
        loginFooter: '© 2026 تطبيق المستوردين. جميع الحقوق محفوظة.',

        signupMainTitle: 'المستوردين',
        signupSubtitle: 'سجل حساب شركتك',
        businessNameLabel: 'اسم الشركة',
        businessNamePlaceholder: 'أدخل اسم الشركة',
        ownerNameLabel: 'الاسم الكامل للمالك',
        ownerNamePlaceholder: 'أدخل الاسم الكامل',
        commerceNumLabel: 'رقم السجل التجاري',
        commerceNumPlaceholder: 'أدخل رقم السجل',
        ninLabel: 'الرقم الوطني للتعريف (NIN)',
        ninPlaceholder: 'أدخل الرقم الوطني',
        importLicenseLabel: 'رخصة الاستيراد',
        commRegisterLabel: 'السجل التجاري',
        idFrontLabel: 'واجهة الهوية',
        idBackLabel: 'خلفية الهوية',
        clickToUpload: 'انقر للرفع',
        liveSelfieVerif: 'التحقق بصورة سيلفي حية',
        liveSelfieDesc: 'يرجى التقاط صورة واضحة لنفسك',
        readyToSubmit: 'جاهز للإرسال',
        retakePhoto: 'إعادة التقاط الصورة',
        clickToOpenCam: 'انقر لفتح الكاميرا',
        phoneLabel: 'الهاتف',
        confirmPasswordLabel: 'تأكيد كلمة المرور',
        confirmPasswordPlaceholder: 'قم بتأكيد كلمة المرور',
        backButton: 'رجوع',
        nextButton: 'التالي',
        registerButton: 'تسجيل الشركة',
        haveAccount: 'لديك حساب بالفعل؟',
        loginLink: 'تسجيل الدخول',
        step1: 'التسجيل',
        step2: 'الوثائق',
        step3: 'سيلفي',
        step4: 'البيانات',

        // Auth Errors
        errInvalidCreds: 'يرجى إدخال بيانات اعتماد صحيحة.',
        errAccountReview: 'حسابك لا يزال قيد المراجعة. يرجى الانتظار 24-48 ساعة.',
        errAccountNotFound: 'الحساب غير موجود.',
        errLoginFailed: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
        errNetwork: 'خطأ في الشبكة: لا يمكن الوصول إلى الخادم أو تم حظره بواسطة CORS.',
        errReqBusinessName: 'اسم الشركة مطلوب.',
        errReqOwnerName: 'الاسم الكامل للمالك مطلوب.',
        errReqCommerceNum: 'رقم السجل التجاري مطلوب.',
        errReqNin: 'الرقم الوطني مطلوب.',
        errNinLength: 'يجب أن يتكون الرقم الوطني من 18 رقمًا بالضبط.',
        errReqIdFront: 'صورة واجهة الهوية مطلوبة.',
        errReqImportLicense: 'رخصة الاستيراد مطلوبة.',
        errReqCommRegister: 'السجل التجاري مطلوب.',
        errReqSelfie: 'صورة السيلفي مطلوبة.',
        errSelfieMissing: 'صورة السيلفي مفقودة أو غير صالحة.',
        errSelfieProcess: 'خطأ في معالجة صورة السيلفي. يرجى إعادة التقاطها.',
        errReqEmail: 'البريد الإلكتروني مطلوب.',
        errInvalidEmail: 'تنسيق البريد الإلكتروني غير صالح.',
        errReqPhone: 'رقم الهاتف مطلوب.',
        errPhoneLength: 'يجب أن يتكون رقم الهاتف من 9 أرقام بعد الرمز.',
        errReqPassword: 'كلمة المرور مطلوبة.',
        errPasswordMismatch: 'كلمات المرور غير متطابقة.',
        errInvalidData: 'بيانات غير صالحة. يرجى التحقق من مدخلاتك.',
        errRegistrationData: 'يرجى تصحيح الأخطاء التالية:',
        errSecurityVerif: 'التحقق الأمني',
        errSentCodeTo: 'لقد أرسلنا رمزًا مكونًا من 6 أرقام إلى',
        errInvalidOtpMsg: 'يرجى إدخال رمز فعال مكون من 6 أرقام.',
        errVerifyOtp: 'رمز غير صالح. يرجى المحاولة مرة أخرى.',
        errOtpResendFailed: 'فشل إعادة إرسال الرمز. يرجى المحاولة مرة أخرى.',
        errOccurredDuringReg: 'حدث خطأ أثناء التسجيل.',

        // Settings
        settingsTitle: 'الإعدادات والملف الشخصي',
        settingsSubtitle: 'إدارة حسابك وتفضيلاتك',
        businessProfile: 'الملف التجاري',
        verificationDocs: 'وثائق التحقق',
        notificationPrefs: 'تفضيلات الإشعارات',
        profilePicture: 'صورة الملف الشخصي',
        language: 'اللغة',
        security: 'الأمان',
        businessName: 'اسم الشركة',
        ownerFullName: 'الاسم الكامل للمالك',
        email: 'البريد الإلكتروني',
        phone: 'الهاتف',
        businessAddress: 'عنوان الشركة',
        taxId: 'الرقم الضريبي',
        website: 'الموقع الإلكتروني',
        saveChanges: 'حفظ التغييرات',
        uploadNew: 'رفع صورة جديدة',
        changePassword: 'تغيير كلمة المرور',
        twoFactorAuth: 'المصادقة الثنائية',
        approved: 'معتمد',
        reupload: 'إعادة الرفع',
        uploaded: 'تم الرفع',
        stayUpdated: 'ابق على اطلاع بأهم الأمور بالنسبة لك',
        emailNotifications: 'إشعارات البريد الإلكتروني',
        pushNotifications: 'الإشعارات الفورية',
        orderUpdates: 'تحديثات الطلبات',
        negotiationMessages: 'رسائل التفاوض',
        promotionsUpdates: 'العروض والتحديثات',
        statusPublished: 'منشور',
        statusDraft: 'مسودة',
        statusPending: 'قيد المراجعة',
        statusHidden: 'مخفي',
        hide: 'إخفاء',
        manageBusinessDesc: 'إدارة التفاصيل الأساسية لعملك',
        verifyIdentityDesc: 'تحقق من هويتك لفتح جميع الميزات',
        roleImporter: 'مستورد',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
        updatePassword: 'تحديث كلمة المرور',
        saving: 'جاري حفظ التغييرات...',
        profileUpdated: 'تم تحديث الملف الشخصي بنجاح',
        errorSaving: 'فشل في حفظ التغييرات',
        update: 'تحديث',
        updatingPassword: 'جاري تحديث كلمة المرور...',
        passwordUpdated: 'تم تحديث كلمة المرور بنجاح!',
        passwordsMismatch: 'كلمات المرور غير متطابقة!'
    },

    fr: {
        // Onboarding
        navDashboard: 'Tableau de bord',
        navLogin: 'Connexion',
        navGetStarted: 'Commencer',
        heroTitle1: 'Le Commerce Mondial',
        heroTitle2: 'Rendu',
        heroTitle3: 'Simple.',
        heroSubtitle1: 'La plateforme la plus puissante pour les importateurs modernes.',
        heroSubtitle2: 'Sécurisée, rapide et conçue pour votre croissance.',
        createFreeAccount: 'Créer votre compte gratuit',
        downloadOnThe: 'Télécharger sur',
        getItOn: 'Obtenir sur',
        appStore: 'App Store',
        googlePlay: 'Google Play',
        footerRights: '© 2026 APPLICATION IMPORTATEURS. TOUS DROITS RÉSERVÉS.',

        // Sidebar
        dashboard: 'Tableau de bord',
        clientCommands: 'Commandes Clients',
        negotiations: 'Négociations',
        myOffers: 'Mes Offres',
        orders: 'Commandes',
        wallet: 'Portefeuille',
        settings: 'Paramètres',

        // Dashboard
        dashboardTitle: 'Tableau de bord',
        dashboardSubtitle: 'Bon retour ! Voici ce qui se passe dans votre entreprise.',
        activeCommands: 'Commandes Actives',
        activeNegotiations: 'Négociations Actives',
        noNegotiationsFound: 'Aucune négociation pour le moment. Commencez à explorer les commandes !',
        selectNegotiation: 'Sélectionnez une conversation pour commencer à négocier',
        relatesToOffer: 'Lié à l\'offre',
        incomingProposal: 'Proposition Entrante',
        totalValue: 'Valeur Totale',
        makeCounterOffer: 'Faire une contre-proposition',
        newPrice: 'Nouveau Prix',
        newQuantity: 'Nouvelle Quantité',
        sendCounterOffer: 'Envoyer la contre-proposition',
        negotiationDesc: 'Examinez les propositions, négociez les prix et finalisez vos transactions commerciales en temps réel.',
        directComm: 'Communication Directe',
        securePayments: 'Paiements Sécurisés',
        priceNeg: 'Négociation de Prix',
        typeAMessage: 'Tapez un message...',
        activeOrders: 'Commandes en Cours',
        pointsBalance: 'Solde de Points',
        earningsOverview: 'Aperçu des Gains',
        monthlyEarnings: 'Tendance des gains mensuels',
        revenueTrend: 'Tendance des gains mensuels',
        requestDetails: 'Détails de la demande',
        searchPlaceholder: 'Rechercher...',
        last6Months: '6 derniers mois',
        last12Months: '12 derniers mois',
        thisYear: 'Cette année',
        ordersByStatus: 'Commandes par Statut',
        completed: 'Terminé',
        inProgress: 'En Cours',
        pending: 'En Attente',
        cancelled: 'Annulé',
        quickActions: 'Actions Rapides',
        createOffer: 'Créer une Offre',
        browseCommands: 'Parcourir les Commandes',
        thisMonth: 'Ce Mois',
        totalEarnings: 'Gains Totaux',
        ordersCompleted: 'Commandes Terminées',
        avgRating: 'Note Moy.',
        recentActivity: 'Activité Récente',
        orderId: 'ID Commande',
        client: 'Client',
        vendor: 'Vendeur',
        action: 'Action',
        amount: 'Montant',
        time: 'Heure',
        status: 'Statut',
        // Months
        jan: 'Jan',
        feb: 'Fév',
        mar: 'Mar',
        apr: 'Avr',
        may: 'Mai',
        jun: 'Juin',
        jul: 'Juil',
        aug: 'Août',
        sep: 'Sep',
        oct: 'Oct',
        nov: 'Nov',
        dec: 'Déc',
        statusNew: 'nouveau',
        statusPaid: 'payé',
        statusNegotiating: 'en négociation',
        actNewProposal: 'Nouvelle proposition reçue',
        actOrderCompleted: 'Commande terminée',
        actPaymentReceived: 'Paiement reçu',
        actNegotiationStarted: 'Négociation commencée',

        // My Offers
        myOffersTitle: 'Mes Offres',
        myOffersSubtitle: 'Gérez vos offres de produits',
        image: 'Image',
        title: 'Titre',
        basePrice: 'Prix de Base',
        availableQty: 'Qté Disponible',
        origin: 'Origine',
        negotiable: 'Négociable',
        actions: 'Actions',
        statusACTIVE: 'Actif',
        statusHIDDEN: 'Masqué',
        loadingOffers: 'Chargement des offres...',
        noOffersFound: 'Aucune offre trouvée. Créez votre première offre !',
        units: 'unités',
        deleteOffer: 'Supprimer l\'Offre',
        deleteOfferMsg: 'Êtes-vous sûr de vouloir supprimer cette offre ? Cette action est irréversible.',
        delete: 'Supprimer',
        keepIt: 'Conserver',

        // Orders
        ordersTitle: 'Commandes',
        ordersSubtitle: 'Gérez vos commandes d\'importation',
        total: 'Total',
        escrowStatus: 'Statut Escrow',
        orderStatus: 'Statut Commande',
        createdAt: 'Créé le',
        viewDetails: 'Voir Détails',
        backToOrders: 'Retour aux Commandes',
        createdOn: 'Créé le',
        orderItems: 'Articles de la Commande',
        shipmentProof: 'Preuve d\'Expédition',
        noShipmentDocs: 'Aucun document pour le moment',
        markAsShipped: 'Marquer comme Expédié',
        inspectionVideo: 'Vidéo d\'Inspection',
        uploadInspectionVideo: 'Uploader la vidéo après expédition',
        uploadVideo: 'Uploader Vidéo',
        escrowDetails: 'Détails Escrow',
        depositAmount: 'Montant Dépôt',
        totalHeld: 'Total Retenu',
        releasedAmount: 'Montant Libéré',
        escrowProgress: 'Progression Escrow',
        actionsCard: 'Actions',
        contactClient: 'Contacter Client',
        escrowHeld: 'retenu',
        escrowReleased: 'libéré',
        orderProcessing: 'traitement',
        orderCompleted: 'terminé',

        // Client Commands
        clientCommandsTitle: 'Commandes Clients',
        clientCommandsSubtitle: 'Parcourez et répondez aux demandes d\'importation',
        searchCommands: 'Rechercher des commandes...',
        allCategories: 'Toutes les Catégories',
        electronics: 'Électronique',
        clothing: 'Vêtements',
        furniture: 'Meubles',
        moreFilters: 'Plus de Filtres',
        launchDate: 'Date de Lancement',
        originWilaya: 'Origine (Wilaya)',
        allLocations: 'Toutes les Régions',
        allStatus: 'Tous les Statuts',
        urgent: 'Urgent',
        normal: 'Normal',
        statusNew2: 'Nouveau',
        budgetRange: 'Budget',
        min: 'Min',
        max: 'Max',
        qty: 'Qté',
        deadline: 'Délai',
        seeMore: 'Voir plus',
        sendProposal: 'Envoyer Proposition',
        commandDetails: 'Détails de la Commande',
        commandId: 'ID Commande',
        product: 'Produit',
        quantity: 'Quantité',
        budget: 'Budget',
        location: 'Lieu',
        category: 'Catégorie',
        budgetRangeLabel: 'Plage de Budget',
        proposedUnitPrice: 'Prix Unitaire Proposé (€)',
        unitPrice: 'Prix par unité (DZD) *',
        enterPricePerUnit: 'Entrez votre prix unitaire',
        yourProposal: 'Votre Message de Proposition',
        quantityOffered: 'Quantité Offerte',
        deliveryTime: 'Délai de Livraison (jours)',
        messageToClient: 'Message au Client',
        describeOffer: 'Décrivez votre offre, garanties de qualité...',
        beSpecific: 'Soyez précis sur la qualité et les conditions.',
        warningContact: 'Attention : Ne partagez pas de coordonnées externes. Notre IA détecte cela et entraînera un bannissement.',
        securityWarning: 'Avertissement de Sécurité',
        saveDraft: 'Brouillon',
        posted2DaysAgo: 'Publié il y a 2 jours',
        posted5DaysAgo: 'Publié il y a 5 jours',
        posted1WeekAgo: 'Publié il y a 1 semaine',
        delivery7to10Days: '7 - 10 jours',
        delivery10to15Days: '10 - 15 jours',
        delivery15to20Days: '15 - 20 jours',
        delivery20to30Days: '20 - 30 jours',
        deliveryMore30Days: '+30 jours',
        publishingOffer: 'Publication de votre offre...',
        updatingOffer: 'Mise à jour de votre offre...',
        createNewOffer: 'Créer une Nouvelle Offre',
        orderTracking: 'Détails de la Commande',
        editOfferTitle: 'Modifier l\'Offre',
        productDetails: 'Détails du Produit',
        pricingQuantity: 'Prix et Quantité',
        imagesOrigin: 'Images et Origine',
        basicInfo: 'Infos de Base',
        mediaOrigin: 'Médias et Origine',
        offerPublishedSuccess: 'Offre Publiée avec Succès !',
        offerUpdatedSuccess: 'Offre Mise à Jour avec Succès !',
        offerPublishedSuccessMsg: 'Votre produit est maintenant en ligne et visible par les clients potentiels.',
        offerUpdatedSuccessMsg: 'Vos modifications ont été enregistrées.',
        done: 'Terminé',
        titleLabel: 'Titre',
        titlePlaceholder: 'ex: Offre de Vestes en Cuir Premium',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Description détaillée du produit...',
        productNameLabel: 'Nom du Produit',
        productNamePlaceholder: 'ex: Veste en Cuir modèle X',
        categoryLabel: 'Catégorie',
        selectCategory: 'Sélectionner une catégorie',
        fashion: 'Mode',
        electronicsCat: 'Électronique',
        homeGarden: 'Maison & Jardin',
        automotive: 'Automobile',
        basePriceLabel: 'Prix de Base ($)',
        availableQtyLabel: 'Quantité Disponible',
        priceNegotiable: 'Le prix est négociable',
        negotiableAgreeMsg: 'En sélectionnant ceci, vous acceptez de recevoir des demandes de négociation.',
        productImages: 'Images du Produit',
        upload: 'Uploader',
        uploadHint: 'Uploadez jusqu\'à 8 images',
        selected: 'sélectionnées',
        originCountry: 'Pays d\'Origine',
        originPlaceholder: 'ex: Italie, Chine',
        preview: 'Aperçu',
        noDescription: 'Pas de description',
        updateOffer: 'Mettre à jour l\'offre',
        publishOffer: 'Publier l\'offre',
        continue: 'Continuer',
        errReqTitle: 'Veuillez entrer un titre pour votre offre',
        errReqDesc: 'Veuillez entrer une description de produit',
        errReqProdName: 'Veuillez entrer un nom de produit',
        errReqCat: 'Veuillez sélectionner une catégorie',
        errReqPrice: 'Veuillez entrer un prix de base valide',
        errReqQty: 'Veuillez entrer une quantité disponible valide',
        errReqImages: 'Veuillez uploader au moins une image du produit',
        errReqOrigin: 'Veuillez entrer le pays d\'origine',
        errMaxImages: 'Maximum 8 images autorisées. Veuillez sélectionner moins de fichiers.',
        brandLogo: 'Importateur',
        logout: 'Se déconnecter',
        discoverDeals: 'Découvrir des offres',
        noOrdersMsg: 'Aucune commande trouvée. Commencez à parcourir les offres pour réaliser votre première transaction !',

        // Auth Pages (Login & SignUp)
        loginTitle: 'importateurs',
        loginSubtitle: 'Bon retour ! Veuillez vous connecter.',
        emailLabel: 'Email',
        emailPlaceholder: 'votre.email@exemple.com',
        passwordLabel: 'Mot de Passe',
        passwordPlaceholder: 'Entrez votre mot de passe',
        rememberMe: 'Se souvenir de moi',
        forgotPassword: 'Mot de passe oublié ?',
        loginButton: 'Se connecter',
        loggingInButton: 'Connexion...',
        noAccount: "Vous n'avez pas de compte ?",
        registerAsBusiness: "S'inscrire en tant qu'entreprise",
        loginFooter: '© 2026 Importateurs. Tous droits réservés.',

        signupMainTitle: 'importateurs',
        signupSubtitle: 'Enregistrez votre compte entreprise',
        businessNameLabel: 'Nom de l\'Entreprise',
        businessNamePlaceholder: 'Entrez le nom de l\'entreprise',
        ownerNameLabel: 'Nom Complet du Propriétaire',
        ownerNamePlaceholder: 'Entrez le nom complet',
        commerceNumLabel: 'Numéro de Registre de Commerce',
        commerceNumPlaceholder: 'Entrez le numéro de registre',
        ninLabel: 'NIN (Numéro d\'Identification National)',
        ninPlaceholder: 'Entrez le NIN',
        importLicenseLabel: 'Licence d\'Importation',
        commRegisterLabel: 'Registre du Commerce',
        idFrontLabel: 'Recto de la Pièce d\'Identité',
        idBackLabel: 'Verso de la Pièce d\'Identité',
        clickToUpload: 'Cliquez pour uploader',
        liveSelfieVerif: 'Vérification Selfie en Direct',
        liveSelfieDesc: 'Veuillez prendre une photo claire de vous-même',
        readyToSubmit: 'Prêt à soumettre',
        retakePhoto: 'Reprendre la photo',
        clickToOpenCam: 'Cliquez pour ouvrir la caméra',
        phoneLabel: 'Téléphone',
        confirmPasswordLabel: 'Confirmer le Mot de Passe',
        confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
        backButton: 'Retour',
        nextButton: 'Suivant',
        registerButton: 'Enregistrer l\'Entreprise',
        haveAccount: 'Vous avez déjà un compte ?',
        loginLink: 'Se connecter',
        step1: 'Inscription',
        step2: 'Documents',
        step3: 'Selfie',
        step4: 'Identifiants',

        // Auth Errors
        errInvalidCreds: 'Veuillez entrer des identifiants valides.',
        errAccountReview: 'Votre compte est toujours en cours d\'examen. Veuillez patienter 24-48 heures.',
        errAccountNotFound: 'Compte introuvable.',
        errLoginFailed: 'Échec de la connexion. Veuillez réessayer.',
        errNetwork: 'Erreur réseau : Le serveur est inaccessible ou bloqué par CORS.',
        errReqBusinessName: 'Le nom de l\'entreprise est requis.',
        errReqOwnerName: 'Le nom complet du propriétaire est requis.',
        errReqCommerceNum: 'Le numéro de registre de commerce est requis.',
        errReqNin: 'Le NIN est requis.',
        errNinLength: 'Le NIN doit comporter exactement 18 chiffres.',
        errReqIdFront: 'L\'image recto de la pièce d\'identité est requise.',
        errReqImportLicense: 'La licence d\'importation est requise.',
        errReqCommRegister: 'Le registre du commerce est requis.',
        errReqSelfie: 'La photo selfie est requise.',
        errSelfieMissing: 'La photo selfie est manquante ou invalide.',
        errSelfieProcess: 'Erreur lors du traitement du selfie. Veuillez le reprendre.',
        errReqEmail: 'L\'email est requis.',
        errInvalidEmail: 'Le format de l\'email est invalide.',
        errReqPhone: 'Le numéro de téléphone est requis.',
        errPhoneLength: 'Le numéro de téléphone doit comporter 9 chiffres après l\'indicatif.',
        errReqPassword: 'Le mot de passe est requis.',
        errPasswordMismatch: 'Les mots de passe ne correspondent pas.',
        errInvalidData: 'Données invalides. Veuillez vérifier vos saisies.',
        errRegistrationData: 'Veuillez corriger les erreurs suivantes :',
        errSecurityVerif: 'Vérification de sécurité',
        errSentCodeTo: 'Nous avons envoyé un code à 6 chiffres à',
        errInvalidOtpMsg: 'Veuillez entrer un code OTP à 6 chiffres valide.',
        errVerifyOtp: 'OTP invalide. Veuillez réessayer.',
        errOtpResendFailed: 'Échec du renvoi de l\'OTP. Veuillez réessayer.',
        errOccurredDuringReg: 'Une erreur s\'est produite lors de l\'inscription.',

        // Settings

        settingsTitle: 'Paramètres et Profil',
        settingsSubtitle: 'Gérez votre compte et vos préférences',
        businessProfile: 'Profil d\'Entreprise',
        verificationDocs: 'Documents de Vérification',
        notificationPrefs: 'Préférences de Notification',
        profilePicture: 'Photo de Profil',
        language: 'Langue',
        security: 'Sécurité',
        businessName: 'Nom de l\'Entreprise',
        ownerFullName: 'Nom Complet du Propriétaire',
        email: 'Email',
        phone: 'Téléphone',
        businessAddress: 'Adresse de l\'Entreprise',
        taxId: 'Numéro d\'Identification Fiscale',
        website: 'Site Web',
        saveChanges: 'Enregistrer',
        uploadNew: 'Uploader',
        changePassword: 'Changer le Mot de Passe',
        twoFactorAuth: 'Authentification à 2 Facteurs',
        approved: 'Approuvé',
        reupload: 'Ré-uploader',
        uploaded: 'Uploadé',
        stayUpdated: 'Restez informé de ce qui compte pour vous',
        emailNotifications: 'Notifications par Email',
        pushNotifications: 'Notifications Push',
        orderUpdates: 'Mises à jour des Commandes',
        negotiationMessages: 'Messages de Négociation',
        promotionsUpdates: 'Promotions et Mises à jour',
        statusPublished: 'Publié',
        statusDraft: 'Brouillon',
        statusPending: 'En attente',
        statusHidden: 'Masqué',
        statusPENDING: 'En attente',
        statusAPPROVED: 'Approuvé',
        statusREJECTED: 'Rejeté',
        pendingActionError: '🔒 Vérification d’identité en cours : Vous êtes actuellement en mode lecture seule. Une fois que notre équipe aura approuvé vos documents, vous aurez un accès complet. Nous vous informerons par e-mail !',
        selectNegotiationPlaceholder: 'Sélectionnez une négociation pour commencer à chatter avec les clients et conclure des affaires.',
        workspaceTitle: 'Votre Espace de Travail',
        proposedPriceLabel: 'Prix Proposé',
        proposedQuantityLabel: 'Quantité Proposée',
        willNotifyEmail: 'La notification sera envoyée à :',
        hide: 'Masquer',
        manageBusinessDesc: 'Gérez les détails de votre entreprise',
        verifyIdentityDesc: 'Vérifiez votre identité pour débloquer toutes les fonctionnalités',
        roleImporter: 'Importateur',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmNewPassword: 'Confirmer le nouveau mot de passe',
        updatePassword: 'Mettre à jour le mot de passe',
        saving: 'Enregistrement...',
        profileUpdated: 'Profil mis à jour avec succès',
        errorSaving: 'Échec de l\'enregistrement',
        update: 'Mettre à jour',
        updatingPassword: 'Mise à jour du mot de passe...',
        passwordUpdated: 'Mot de passe mis à jour avec succès !',
        passwordsMismatch: 'Les mots de passe ne correspondent pas !'
    }

};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState('en');

    const setLanguage = (lang) => {
        if (lang === language) return;
        setLanguageState(lang);
    };

    const dir = language === 'ar' ? 'rtl' : 'ltr';
    const t = translations[language] || translations.en;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
            {children}
        </LanguageContext.Provider>
    );
};


export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};

export default LanguageContext;
